### PR TITLE
Fix zero read at EOF in readByteArrays().

### PR DESCRIPTION
**Pull request by balamurugana**

### CODE REVIEW

**Comment by harshavardhana** [comment]
I tried this rebase with Minio master three different behaviors with three different parquet files attaching all of them here - you can find them at `mc ls play/testbucket/` 

with `userdata1.parquet` server crashes with 

> 2019-01-11 19:11:18.435341 I | http: panic serving 127.0.0.1:40020: interface conversion: interface {} is nil, not []uint8

with `people.parqut` server crashes with 

> 2019-01-11 19:15:08.054964 I | http: panic serving 127.0.0.1:40064: interface conversion: interface {} is nil, not int64

with `testdata.parquet` 

> 2019-01-11 19:15:56.474708 I | http: panic serving 127.0.0.1:40094: runtime error: slice bounds out of range

**Comment by harshavardhana** [comment]
[parquet-files.zip](https://github.com/minio/parquet-go/files/2751656/parquet-files.zip) - attaching it here as well.

**Comment by balamurugana** [comment]
All files are corrupted parquet files.

**Comment by harshavardhana** [comment]
What they work fine with S3 ?

**Comment by harshavardhana** [comment]
What they work fine with S3 ?

**Comment by harshavardhana** [comment]
You can also get the parquet files from `s3/sjm-airlines-1` bucket 

Here is what I would expect from our implementation

```
~ mc sql -e "select * from s3object" s3/sjm-airlines-1/people.parquet
{"name":"Michael","age":31}
{"name":"Andy","age":30}
{"name":"Justin","age":19}
```

```
~ mc sql -e "select * from s3object" s3/sjm-airlines-1/testdata.parquet
{"one":-1e0,"three":true,"two":"Zm9v","__index_level_0__":"YQ=="}
{"three":false,"two":"YmFy","__index_level_0__":"Yg=="}
{"one":2.5e0,"three":true,"two":"YmF6","__index_level_0__":"Yw=="}
```

```
~ mc sql -e "select * from s3object" s3/sjm-airlines-1/userdata1.parquet | mc head
{"registration_dttm":45331434715132002751293952,"id":1,"first_name":"Amanda","last_name":"Jordan","email":"ajordan0@com.com","gender":"Female","ip_address":"1.197.201.2","cc":"6759521864920116","country":"Indonesia","birthdate":"3/8/1971","salary":49756.53e0,"title":"Internal Auditor","comments":"1E+02"}
{"registration_dttm":45331434715164916751293952,"id":2,"first_name":"Albert","last_name":"Freeman","email":"afreeman1@is.gd","gender":"Male","ip_address":"218.111.175.34","cc":"","country":"Canada","birthdate":"1/16/1968","salary":150280.17e0,"title":"Accountant IV","comments":""}
{"registration_dttm":45331434715107644751293952,"id":3,"first_name":"Evelyn","last_name":"Morgan","email":"emorgan2@altervista.org","gender":"Female","ip_address":"7.161.136.94","cc":"6767119071901597","country":"Russia","birthdate":"2/1/1960","salary":144972.51e0,"title":"Structural Engineer","comments":""}
{"registration_dttm":45331434715105654751293952,"id":4,"first_name":"Denise","last_name":"Riley","email":"driley3@gmpg.org","gender":"Female","ip_address":"140.35.109.83","cc":"3576031598965625","country":"China","birthdate":"4/8/1997","salary":90263.05e0,"title":"Senior Cost Accountant","comments":""}
{"registration_dttm":45331434715121804751293952,"id":5,"first_name":"Carlos","last_name":"Burns","email":"cburns4@miitbeian.gov.cn","gender":"","ip_address":"169.113.235.40","cc":"5602256255204850","country":"South Africa","birthdate":"","title":"","comments":""}
{"registration_dttm":45331434715130027751293952,"id":6,"first_name":"Kathryn","last_name":"White","email":"kwhite5@google.com","gender":"Female","ip_address":"195.131.81.179","cc":"3583136326049310","country":"Indonesia","birthdate":"2/25/1983","salary":69227.11e0,"title":"Account Executive","comments":""}
{"registration_dttm":45331434715134261751293952,"id":7,"first_name":"Samuel","last_name":"Holmes","email":"sholmes6@foxnews.com","gender":"Male","ip_address":"232.234.81.197","cc":"3582641366974690","country":"Portugal","birthdate":"12/18/1987","salary":14247.62e0,"title":"Senior Financial Analyst","comments":""}
{"registration_dttm":45331434715127899751293952,"id":8,"first_name":"Harry","last_name":"Howell","email":"hhowell7@eepurl.com","gender":"Male","ip_address":"91.235.51.73","cc":"","country":"Bosnia and Herzegovina","birthdate":"3/1/1962","salary":186469.43e0,"title":"Web Developer IV","comments":""}
{"registration_dttm":45331434715117446751293952,"id":9,"first_name":"Jose","last_name":"Foster","email":"jfoster8@yelp.com","gender":"Male","ip_address":"132.31.53.61","cc":"","country":"South Korea","birthdate":"3/27/1992","salary":231067.84e0,"title":"Software Test Engineer I","comments":"1E+02"}
{"registration_dttm":45331434715170060751293952,"id":10,"first_name":"Emily","last_name":"Stewart","email":"estewart9@opensource.org","gender":"Female","ip_address":"143.28.251.245","cc":"3574254110301671","country":"Nigeria","birthdate":"1/28/1997","salary":27234.28e0,"title":"Health Coach IV","comments":""}
...
```

**Comment by harshavardhana** [comment]
Notice I am using mc with this PR https://github.com/minio/mc/pull/2643

**Comment by balamurugana** [comment]
I downloaded `people.parquet` from AWS S3 and it works fine with this PR i.e. This PR is nothing to wrong.

There are two problems here.
1. Previously given parquet files were corrupted. e.g. `people.parquet` from AWS S3 is correct and clean.
```bash
$ md5sum people.parquet /tmp/home/harsha/Downloads/people.parquet 
72ebc15f5b9eb6be0cf997992d350ae0  people.parquet
3b6f756feaea973403bcc3f91408e07f  /tmp/home/harsha/Downloads/people.parquet
```

This needs to be avoided (Also those comments were removed as well).

2. `getObjectNInfo()` works weirdly.  I updated https://github.com/minio/minio/pull/7067 to translate offset/length to Range.  It works OK with `people.parquet`.  However `getObjectNInfo()` is still weird. For `offset=-8` and `length=4`, previously it was `&cmd.HTTPRangeSpec{IsSuffixLength:true, Start:-8, End:4}`, now `&cmd.HTTPRangeSpec{IsSuffixLength:true, Start:-8, End:-4}` is sent to `getObjectNInfo()`.  Expected: `[229 0 0 0]`, Got: `[229 0 0 0 80 65 82 49]`.
Actual problem was for `offset=150` and `length=90`, previously I got `[]`, now `range = &cmd.HTTPRangeSpec{IsSuffixLength:false, Start:150, End:240}`, got `[21 4 21 48 21 46 76 21 6 21 4 18 0 0 24 4 31 0 9 1 60 30 0 0 0 0 0 0 0 19 0 0 0 0 0 0 0 21 0 21 20 21 24 44 21 6 21 4 21 6 21 6 28 24 8 31 0 0 0 0 0 0 0 24 8 19 0 0 0 0 0 0 0 22 0 0 0 0 10 36 2 0 0 0 6 1 2 3 36 0 38]` which works though.

**Comment by harshavardhana** [comment]
> 1. Previously given parquet files were corrupted. e.g. `people.parquet` from AWS S3 is correct and clean.

yes, that is correct, I have auto encryption enabled so I copied files from backend directory which will look corrupted. Instead, I copied directly from Minio to S3. will check the recent updates to the PR and let you know.

**Comment by harshavardhana** [comment]
I tried all the three parquet files they seem to be working fine on PR minio/minio#7067

**Review by harshavardhana — APPROVED** [review]
LGTM tested

**Pull request merged**
